#include<iostream>
using namespace std;

int main()
{
    // Arthematic and Assignement Operator {=,+= , -=, *=, /=, %=}
    
 //= operator
int x = 4; 
cout<<"=:"<<x<<endl;
    
//+= Operator
x +=3;
cout<<"+=:"<<x<<endl;

//-= Operator
x -= 4;
cout<<"-=:"<<x<<endl;

//*= Operator
x *= 3;
cout<<"*=:"<<x<<endl;

// /= Operator
x /= 4;
cout<<"/=:"<<x<<endl;

// %= Operator
x %= 2;
cout<<"%=:"<<x<<endl;

}